<?php

namespace Webservice\MainBundle\Repository;

/**
 * FeedbackSceanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedbackSceanceRepository extends \Doctrine\ORM\EntityRepository
{
}
