<?php

namespace Webservice\MainBundle\Repository;

/**
 * FeedbackUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedbackUserRepository extends \Doctrine\ORM\EntityRepository
{
}
