<?php

namespace Webservice\MainBundle\Repository;

/**
 * UserSeanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserSeanceRepository extends \Doctrine\ORM\EntityRepository
{
}
