services:
    services.users:
        class: Webservice\ServicesBundle\Services\Users\Users

    services.twitter:
        class: Webservice\ServicesBundle\Services\Twitter\Twitter

    services.film:
        class: Webservice\ServicesBundle\Services\Film\Films
        arguments: ["@doctrine.orm.default_entity_manager", "@serializer"]

    services.message:
        class: Webservice\ServicesBundle\Services\Message\Messages
        arguments: ["@doctrine.orm.default_entity_manager", "@serializer"]

    services.feedBack:
        class: Webservice\ServicesBundle\Services\FeedBack\FeedBacks
        arguments: ["@doctrine.orm.default_entity_manager", "@serializer"]